// ============================================================
// EXPORT FUNCTIONS - REPORT GENERATOR & DATA DOWNLOAD
// ============================================================

function exportPDF() {
    const data = window.currentEvidenceData;
    if (!data || !data.ioc) {
        alert('Please investigate an IOC first before exporting a PDF report.');
        return;
    }

    const ioc = data.ioc || {};
    const risk = data.risk || {};
    const providers = data.providers || {};
    const enrichment = data.enrichment || {};
    const summary = data.ai_summary || {};
    const timestamp = formatDate(data.timestamp || new Date().toISOString());

    const printWin = window.open('', '_blank', 'width=900,height=800');
    if (!printWin) {
        alert('Pop-up blocked! Please allow pop-ups for this site to generate the printable PDF dossier.');
        return;
    }

    const html = `
    <!DOCTYPE html>
    <html>
    <head>
        <title>Threat Intel Dossier - ${escapeHTML(ioc.value || 'Report')}</title>
        <style>
            body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; color: #1e293b; line-height: 1.5; padding: 40px; }
            .header { border-bottom: 2px solid #334155; padding-bottom: 20px; margin-bottom: 30px; display: flex; justify-content: space-between; align-items: flex-end; }
            .header h1 { font-size: 24px; margin: 0; color: #0f172a; }
            .header p { margin: 4px 0 0; color: #64748b; font-size: 13px; }
            .badge { padding: 6px 14px; border-radius: 6px; font-weight: bold; font-size: 14px; color: #fff; background: ${risk.color || '#3b82f6'}; }
            .section { margin-bottom: 30px; page-break-inside: avoid; }
            .section h2 { font-size: 16px; color: #334155; border-bottom: 1px solid #cbd5e1; padding-bottom: 8px; margin-bottom: 14px; text-transform: uppercase; letter-spacing: 0.5px; }
            .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }
            .box { background: #f8fafc; border: 1px solid #e2e8f0; padding: 16px; border-radius: 6px; }
            .box .label { font-size: 11px; color: #64748b; text-transform: uppercase; font-weight: 600; margin-bottom: 4px; }
            .box .val { font-size: 15px; font-weight: 700; color: #0f172a; word-break: break-all; }
            table { width: 100%; border-collapse: collapse; margin-top: 10px; }
            th, td { text-align: left; padding: 10px; border-bottom: 1px solid #e2e8f0; font-size: 13px; }
            th { background: #f1f5f9; color: #475569; font-weight: 600; }
            .footer { margin-top: 50px; padding-top: 20px; border-top: 1px solid #e2e8f0; font-size: 11px; color: #94a3b8; text-align: center; }
            @media print {
                body { padding: 20px; }
                .no-print { display: none; }
            }
        </style>
    </head>
    <body>
        <div class="no-print" style="margin-bottom:20px;text-align:right;">
            <button onclick="window.print()" style="background:#2563eb;color:#fff;border:none;padding:10px 20px;font-size:14px;font-weight:600;border-radius:6px;cursor:pointer;">Print / Save as PDF</button>
            <button onclick="window.close()" style="background:#e2e8f0;color:#334155;border:none;padding:10px 20px;font-size:14px;font-weight:600;border-radius:6px;cursor:pointer;margin-left:10px;">Close</button>
        </div>

        <div class="header">
            <div>
                <h1>Threat Intelligence Investigation Dossier</h1>
                <p>Generated by Threat Intel Workbench Pro · ID: ${data.investigation_id || 'N/A'}</p>
            </div>
            <div class="badge">${escapeHTML(risk.verdict || 'UNKNOWN')} (${risk.score || 0}/100)</div>
        </div>

        <div class="section">
            <h2>Executive Overview</h2>
            <div class="grid">
                <div class="box">
                    <div class="label">Indicator of Compromise (IOC)</div>
                    <div class="val">${escapeHTML(ioc.value || 'N/A')}</div>
                </div>
                <div class="box">
                    <div class="label">Indicator Type & Timestamp</div>
                    <div class="val" style="text-transform:uppercase;">${escapeHTML(ioc.type || 'unknown')} · ${timestamp}</div>
                </div>
            </div>
            ${summary.text ? `
            <div class="box" style="margin-top:16px;">
                <div class="label">AI Synthesis & Analysis</div>
                <div style="font-size:13px;color:#334155;margin-top:6px;line-height:1.6;">${escapeHTML(summary.text)}</div>
            </div>` : ''}
        </div>

        <div class="section">
            <h2>Provider Telemetry Breakdown</h2>
            <table>
                <thead>
                    <tr>
                        <th>Provider</th>
                        <th>Status</th>
                        <th>Detections / Metrics</th>
                        <th>Scan / Last Seen</th>
                    </tr>
                </thead>
                <tbody>
                    ${Object.entries(providers).map(([key, prov]) => `
                    <tr>
                        <td style="font-weight:600;text-transform:capitalize;">${key}</td>
                        <td style="color:${prov.success ? '#16a34a' : '#dc2626'};font-weight:600;">${prov.success ? 'Success' : 'Failed'}</td>
                        <td>${prov.detections !== undefined ? prov.detections + '/' + (prov.total || 72) + ' detections' : prov.abuse_score !== undefined ? prov.abuse_score + '% abuse confidence' : prov.pulses !== undefined ? prov.pulses + ' threat pulses' : prov.error || 'N/A'}</td>
                        <td>${formatDate(prov.scan_date || data.timestamp)}</td>
                    </tr>
                    `).join('')}
                </tbody>
            </table>
        </div>

        ${enrichment.geolocation || enrichment.asn ? `
        <div class="section">
            <h2>Infrastructure & Geolocation</h2>
            <div class="grid">
                ${enrichment.geolocation ? `
                <div class="box">
                    <div class="label">Geolocation Details</div>
                    <div class="val" style="font-size:14px;">${escapeHTML(enrichment.geolocation.city || '')} ${escapeHTML(enrichment.geolocation.country || '')}</div>
                    <div style="font-size:12px;color:#64748b;margin-top:4px;">ISP: ${escapeHTML(enrichment.geolocation.isp || 'N/A')}</div>
                </div>` : ''}
                ${enrichment.asn ? `
                <div class="box">
                    <div class="label">Autonomous System (ASN)</div>
                    <div class="val" style="font-size:14px;">${escapeHTML(enrichment.asn.asn || 'N/A')}</div>
                    <div style="font-size:12px;color:#64748b;margin-top:4px;">Org: ${escapeHTML(enrichment.asn.as_name || 'N/A')}</div>
                </div>` : ''}
            </div>
        </div>` : ''}

        <div class="footer">
            Confidential Threat Intelligence Dossier · Generated on ${new Date().toUTCString()} · Threat Intel Workbench
        </div>
    </body>
    </html>
    `;

    printWin.document.open();
    printWin.document.write(html);
    printWin.document.close();
}

function exportCSV() {
    const data = window.currentEvidenceData;
    if (!data || !data.ioc) {
        alert('Please investigate an IOC first before exporting CSV data.');
        return;
    }

    const ioc = data.ioc || {};
    const risk = data.risk || {};
    const providers = data.providers || {};
    const enrichment = data.enrichment || {};

    const rows = [
        ['Field', 'Value'],
        ['IOC Value', ioc.value || ''],
        ['IOC Type', ioc.type || ''],
        ['Risk Verdict', risk.verdict || ''],
        ['Risk Score', risk.score || 0],
        ['Confidence Score', risk.confidence || 0],
        ['Timestamp', data.timestamp || ''],
        ['Processing Time', data.processing_time || ''],
        ['Country', enrichment.geolocation?.country || ''],
        ['ISP', enrichment.geolocation?.isp || ''],
        ['ASN', enrichment.asn?.asn || ''],
        ['ASN Organization', enrichment.asn?.as_name || '']
    ];

    Object.entries(providers).forEach(([key, prov]) => {
        if (prov && prov.success) {
            rows.push([`${key}_status`, 'success']);
            if (prov.detections !== undefined) rows.push([`${key}_detections`, prov.detections]);
            if (prov.abuse_score !== undefined) rows.push([`${key}_abuse_score`, prov.abuse_score]);
            if (prov.pulses !== undefined) rows.push([`${key}_pulses`, prov.pulses]);
        } else if (prov) {
            rows.push([`${key}_status`, 'failed']);
            rows.push([`${key}_error`, prov.error || '']);
        }
    });

    const csvContent = rows.map(r => r.map(cell => `"${String(cell).replace(/"/g, '""')}"`).join(',')).join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `threat-intel-${ioc.value || 'export'}-${Date.now()}.csv`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}

function exportJSON() {
    if (typeof downloadEvidenceJSON === 'function') {
        downloadEvidenceJSON();
    } else if (window.currentEvidenceData) {
        const jsonStr = JSON.stringify(window.currentEvidenceData, null, 2);
        const blob = new Blob([jsonStr], { type: 'application/json' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `threat-intel-${window.currentEvidenceData?.ioc?.value || 'export'}-${Date.now()}.json`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    } else {
        alert('No data available to export.');
    }
}

function escapeHTML(str) {
    if (!str) return '';
    return String(str).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#039;');
}

// Export functions to global scope
window.exportPDF = exportPDF;
window.exportCSV = exportCSV;
window.exportJSON = exportJSON;

// ============================================================
// AI REPORT EXPORT & SLACK/EMAIL ALERT GENERATOR (Priority 5 & 7)
// ============================================================
function openAIReportModal(initialFormat = 'executive') {
    const data = window.currentEvidenceData;
    if (!data || !data.ioc) {
        alert('Please investigate an indicator first before generating an AI Report.');
        return;
    }

    let modal = document.getElementById('ai-report-modal');
    if (!modal) {
        const modalHtml = `
        <div id="ai-report-modal" style="position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,0.75);backdrop-filter:blur(8px);z-index:10000;display:flex;align-items:center;justify-content:center;padding:20px;">
            <div style="width:100%;max-width:750px;background:var(--bg-card);border:1px solid rgba(139,92,246,0.4);border-radius:16px;box-shadow:0 24px 64px rgba(0,0,0,0.8);display:flex;flex-direction:column;max-height:85vh;overflow:hidden;">
                <div style="padding:16px 20px;background:rgba(30,41,59,0.8);border-bottom:1px solid var(--border);display:flex;justify-content:space-between;align-items:center;">
                    <div style="display:flex;align-items:center;gap:10px;">
                        <i class="fa-solid fa-wand-magic-sparkles" style="color:#c084fc;font-size:20px;"></i>
                        <div>
                            <h3 style="margin:0;font-size:16px;color:#fff;">AI Smart Report & Alert Generator</h3>
                            <span style="font-size:11px;color:#a855f7;">Groq Llama 3.3 70B Multi-Format Synthesis</span>
                        </div>
                    </div>
                    <button onclick="document.getElementById('ai-report-modal').style.display='none'" style="background:transparent;border:none;color:var(--text-dim);font-size:18px;cursor:pointer;"><i class="fa-solid fa-xmark"></i></button>
                </div>
                <div style="padding:16px 20px;border-bottom:1px solid var(--border);display:flex;gap:8px;flex-wrap:wrap;background:rgba(15,23,42,0.6);">
                    <button class="ai-fmt-btn active" data-fmt="executive" style="padding:6px 14px;border-radius:8px;border:1px solid rgba(139,92,246,0.5);background:rgba(139,92,246,0.2);color:#fff;font-size:12px;font-weight:600;cursor:pointer;"><i class="fa-solid fa-briefcase"></i> Executive Summary</button>
                    <button class="ai-fmt-btn" data-fmt="technical" style="padding:6px 14px;border-radius:8px;border:1px solid var(--border);background:rgba(255,255,255,0.05);color:var(--text-light);font-size:12px;cursor:pointer;"><i class="fa-solid fa-code"></i> Technical Report</button>
                    <button class="ai-fmt-btn" data-fmt="alert" style="padding:6px 14px;border-radius:8px;border:1px solid var(--border);background:rgba(255,255,255,0.05);color:var(--text-light);font-size:12px;cursor:pointer;"><i class="fa-solid fa-bell"></i> Slack/Email Alert (Priority 7)</button>
                    <button class="ai-fmt-btn" data-fmt="timeline" style="padding:6px 14px;border-radius:8px;border:1px solid var(--border);background:rgba(255,255,255,0.05);color:var(--text-light);font-size:12px;cursor:pointer;"><i class="fa-solid fa-clock-rotate-left"></i> IR Timeline (Priority 8)</button>
                </div>
                <div id="ai-report-content" style="flex:1;padding:20px;overflow-y:auto;font-family:var(--font-mono);font-size:13px;line-height:1.6;color:var(--text);white-space:pre-wrap;background:rgba(15,23,42,0.9);">
                    Generating AI dossier...
                </div>
                <div style="padding:14px 20px;background:rgba(30,41,59,0.8);border-top:1px solid var(--border);display:flex;justify-content:flex-end;gap:10px;">
                    <button id="ai-report-copy-btn" style="padding:8px 16px;border-radius:8px;background:rgba(59,130,246,0.2);border:1px solid #3b82f6;color:#60a5fa;font-weight:600;font-size:13px;cursor:pointer;"><i class="fa-regular fa-copy"></i> Copy to Clipboard</button>
                    <button id="ai-report-dl-btn" style="padding:8px 16px;border-radius:8px;background:linear-gradient(135deg, #8b5cf6 0%, #3b82f6 100%);border:none;color:#fff;font-weight:600;font-size:13px;cursor:pointer;"><i class="fa-solid fa-download"></i> Download Report</button>
                </div>
            </div>
        </div>
        `;
        document.body.insertAdjacentHTML('beforeend', modalHtml);
        modal = document.getElementById('ai-report-modal');

        // Bind format tabs
        const fmtBtns = modal.querySelectorAll('.ai-fmt-btn');
        fmtBtns.forEach(btn => {
            btn.addEventListener('click', () => {
                fmtBtns.forEach(b => { b.classList.remove('active'); b.style.background='rgba(255,255,255,0.05)'; b.style.color='var(--text-light)'; b.style.borderColor='var(--border)'; });
                btn.classList.add('active');
                btn.style.background='rgba(139,92,246,0.2)'; btn.style.color='#fff'; btn.style.borderColor='rgba(139,92,246,0.5)';
                const fmt = btn.getAttribute('data-fmt');
                fetchReportContent(fmt);
            });
        });

        const copyBtn = document.getElementById('ai-report-copy-btn');
        if (copyBtn) {
            copyBtn.addEventListener('click', () => {
                const contentDiv = document.getElementById('ai-report-content');
                const text = contentDiv ? (contentDiv.dataset.rawReport || contentDiv.innerText) : '';
                navigator.clipboard.writeText(text).then(() => {
                    const oldHtml = copyBtn.innerHTML;
                    copyBtn.innerHTML = '<i class="fa-solid fa-check"></i> Copied!';
                    setTimeout(() => copyBtn.innerHTML = oldHtml, 2000);
                });
            });
        }

        const dlBtn = document.getElementById('ai-report-dl-btn');
        if (dlBtn) {
            dlBtn.addEventListener('click', () => {
                const contentDiv = document.getElementById('ai-report-content');
                const text = contentDiv ? (contentDiv.dataset.rawReport || contentDiv.innerText) : '';
                const activeBtn = modal.querySelector('.ai-fmt-btn.active');
                const fmt = activeBtn ? activeBtn.getAttribute('data-fmt') : 'report';
                const blob = new Blob([text], { type: 'text/markdown;charset=utf-8' });
                const url = URL.createObjectURL(blob);
                const a = document.createElement('a');
                a.href = url;
                a.download = `AI-Dossier-${window.currentEvidenceData?.ioc?.value || 'IOC'}-${fmt}.md`;
                document.body.appendChild(a);
                a.click();
                document.body.removeChild(a);
                URL.revokeObjectURL(url);
            });
        }
    }

    modal.style.display = 'flex';
    // Trigger initial format load
    const activeBtn = modal.querySelector(`.ai-fmt-btn[data-fmt="${initialFormat}"]`);
    if (activeBtn) activeBtn.click();
    else fetchReportContent(initialFormat);
}

async function fetchReportContent(format = 'executive') {
    const contentDiv = document.getElementById('ai-report-content');
    if (!contentDiv) return;
    contentDiv.innerHTML = `<div style="text-align:center;padding:40px;color:var(--text-dim);"><i class="fa-solid fa-spinner fa-spin" style="font-size:24px;margin-bottom:10px;display:block;"></i> Generating AI ${format.toUpperCase()} report...</div>`;

    try {
        const payloadData = typeof sanitizeForAI === 'function' ? sanitizeForAI(window.currentEvidenceData) : window.currentEvidenceData;
        const response = await fetch('/api/export/ai-brief', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ data: payloadData, format })
        });
        const result = await response.json();
        if (result.success && result.report) {
            contentDiv.dataset.rawReport = result.report;
            contentDiv.innerHTML = typeof parseMarkdown === 'function' ? parseMarkdown(result.report) : result.report;
        } else {
            contentDiv.innerHTML = `<span style="color:var(--danger)">Error: ${result.error || result.message || 'Could not generate report.'}</span>`;
        }
    } catch (err) {
        contentDiv.innerHTML = '<span style="color:var(--danger)">Failed to communicate with AI Export service.</span>';
        console.error('AI Report error:', err);
    }
}

window.openAIReportModal = openAIReportModal;